name: Build Docker Images
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        run: |
          for svc in lidar-capture fft-analyzer mode-classifier; do
            docker buildx build \
              -t ghcr.io/${{ github.repository_owner }}/$svc:latest \
              --push ./services/$svc
          done
